// <auto-generated />
using System;
using CadastroCedulas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CadastroCedulas.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210108183516_AtualizaTipoCedula")]
    partial class AtualizaTipoCedula
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CadastroCedulas.Models.CaixaEletronico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CedulaId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCaixa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CaixaEletronico");
                });

            modelBuilder.Entity("CadastroCedulas.Models.Cedula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CaixaEletronicoId")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaixaEletronicoId");

                    b.ToTable("Cedulas");
                });

            modelBuilder.Entity("CadastroCedulas.Models.Cedula", b =>
                {
                    b.HasOne("CadastroCedulas.Models.CaixaEletronico", null)
                        .WithMany("Cedulas")
                        .HasForeignKey("CaixaEletronicoId");
                });
#pragma warning restore 612, 618
        }
    }
}
